# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General info
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: info.svg
          user: skyzyx
          template: classic
          base: header, repositories, metadata
          repositories: 250
          config_timezone: America/Denver
          config_padding: 20

      - name: Achievements
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: achievements.svg
          base: ""
          user: skyzyx
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          config_display: columns
          config_timezone: America/Denver
          config_padding: 20

      - name: Habits
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits.svg
          base: ""
          user: skyzyx
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 60
          plugin_habits_from: 500
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          config_display: columns
          config_timezone: America/Denver
          config_padding: 20

      - name: Languages
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg
          base: ""
          user: skyzyx
          plugin_languages: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 60
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          config_display: columns
          config_timezone: America/Denver
          config_padding: 20

      - name: Reactions
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: reactions.svg
          base: ""
          user: skyzyx
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          config_display: columns
          config_timezone: America/Denver
          config_padding: 20

      - name: Sponsorships
        uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: sponsorships.svg
          base: ""
          user: skyzyx
          plugin_sponsorships: yes
          plugin_sponsorships_sections: sponsorships
          plugin_sponsorships_size: 64
          config_display: columns
          config_timezone: America/Denver
          config_padding: 20
