name: Metrics
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: skyzyx/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
